
title: NTokenizers
description: Documentation for the NTokenizers library
markdown: kramdown

# Sidebar configuration
sidebar:
  nav:
    - title: "Home"
      url: "/NTokenizers.Extensions.Spectre.Console"
    - title: "C#"
      url: "csharp"
    - title: "Json"
      url: "json"
    - title: "Markdown"
      url: "markdown"
    - title: "Sql"
      url: "sql"
    - title: "Typescript/Javascript"
      url: "typescript"
    - title: "Xml"
      url: "xml"
    - title: "Yaml"
      url: "yaml"
    - title: "AI Example"
      url: "ai"

# Breadcrumb
breadcrumb_home_label : "Home"
breadcrumb_separator  : ">"